upstream backend {
    server 10.11.1.74:8000;
    server 10.12.0.245:8000;
}

server {
    listen 80;
    server_name _;

    location / {
        add_header X-Upstream $upstream_addr always;
        proxy_pass http://backend;
    }
}