---
- name: Proxy (Samba + Nginx)
  hosts: smbserver
  become: true
  roles:
   - samba-server
   - nginx-proxy

- name: Web nodes (autofs + python)
  hosts: smbclient
  become: true
  roles:
    - samba-client
    - python-server